name: React App Deployment # name of the workflo

permissions:
    contents: read
    pages: write
    id-token: write


on:
  push:
    branches:
      - deploy-react-app # branch name

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20]

        steps: 
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Install and build
              run: npm install && npm build
            
            - name: Upload artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                name: "github-pages"
                path: "build"

            - name: Deploy
              uses: actions/deploy-pages@v4
              

